### ISSUE TITLE
Docker grunt test does not spawn selenium chrome browser.

### ISSUE THREAD

**Issue by Ouwen** [Ouwen/hikari#1]
When grunt test is run, protractor waits for the selenium chrome browser to spawn. This never happens and the tests timeout.

```
Running "protractor:chrome" (protractor) task
[launcher] Running 1 instances of WebDriver

------------------------------------
[chrome #1a] PID: 119
[chrome #1a] Specs: /src/e2e/login/login.spec.js
[chrome #1a] 
[chrome #1a] Using ChromeDriver directly...
[chrome #1a] ERROR - Unable to start a WebDriver session.
[chrome #1a] 
[chrome #1a] /src/node_modules/selenium-webdriver/http/util.js:87
[chrome #1a]           Error('Timed out waiting for the WebDriver server at ' + url));
[chrome #1a]           ^
[chrome #1a] Error: Timed out waiting for the WebDriver server at http://127.0.0.1:57413/
[chrome #1a]     at Error (native)
[chrome #1a]     at onResponse (/src/node_modules/selenium-webdriver/http/util.js:87:11)
[chrome #1a]     at /src/node_modules/selenium-webdriver/http/util.js:42:21
[chrome #1a]     at /src/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
[chrome #1a]     at ClientRequest.<anonymous> (/src/node_modules/selenium-webdriver/http/index.js:145:7)
[chrome #1a]     at emitOne (events.js:77:13)
[chrome #1a]     at ClientRequest.emit (events.js:169:7)
[chrome #1a]     at Socket.socketErrorListener (_http_client.js:267:9)
[chrome #1a]     at emitOne (events.js:77:13)
[chrome #1a]     at Socket.emit (events.js:169:7)
[chrome #1a] ==== async task ====
[chrome #1a] WebDriver.createSession()
[chrome #1a]     at Function.webdriver.WebDriver.acquireSession_ (/src/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
[chrome #1a]     at Function.webdriver.WebDriver.createSession (/src/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
[chrome #1a]     at new Driver (/src/node_modules/selenium-webdriver/chrome.js:477:36)
[chrome #1a]     at Object.createDriver (/src/node_modules/selenium-webdriver/chrome.js:453:10)
[chrome #1a]     at DirectDriverProvider.getNewDriver (/src/node_modules/grunt-protractor-runner/node_modules/protractor/lib/driverProviders/direct.js:68:23)
[chrome #1a]     at Runner.createBrowser (/src/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:180:37)
[chrome #1a]     at /src/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:257:21
[chrome #1a]     at _fulfilled (/src/node_modules/grunt-protractor-runner/node_modules/q/q.js:797:54)
[chrome #1a]     at self.promiseDispatch.done (/src/node_modules/grunt-protractor-runner/node_modules/q/q.js:826:30)
```

**Comment by Ouwen** [comment]
This is likely due to docker port config. 

Try setting direct connect to false and spawning a standalone selenium server.

https://github.com/angular/protractor/blob/master/docs/referenceConf.js
