### ISSUE TITLE
Docker grunt build cannot run imagemin task.

### ISSUE THREAD

**Issue by Ouwen** [Ouwen/hikari#2]
When running grunt build the imagemin task fails. This is likely because the jpeg-tran package does not properly install during the `npm install` phase.

```
> jpegtran-bin@3.1.0 postinstall /src/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ The `/src/node_modules/jpegtran-bin/vendor/jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="/src/node_modules/jpegtran-bin/vendor" --bindir="/src/node_modules/jpegtran-bin/vendor" && make install
Command failed: /bin/sh -c ./configure --disable-shared --prefix="/src/node_modules/jpegtran-bin/vendor" --bindir="/src/node_modules/jpegtran-bin/vendor"
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN prefer global jshint@2.8.0 should be installed with -g
```

```
        Warning: Running "imagemin:dist" (imagemin) task
    Warning: Error: Error: write EPIPE/src/node_modules/jpegtran-bin/vendor/jpegtran: 1: /src/node_modules/jpegtran-bin/vendor/jpegtran: Syntax error: "(" unexpected
     in file client/assets/images/background.jpg Use --force to continue.

    Aborted due to warnings.


    Execution Time (2016-08-12 15:44:24 UTC-0)
    loading tasks                   206ms  ▇▇ 5%
    loading grunt-contrib-imagemin   4.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 93%
    imagemin:dist                    98ms  ▇ 2%
    Total 4.4s Use --force to continue.

        Aborted due to warnings.
```

**Comment by Ouwen** [comment]
Fixed by correctly installing `jpegtran`
